### ISSUE TITLE
BREAKS when run on a MODx site installed within a subdirectory

### ISSUE THREAD

**Issue by 01iv3r** [splittingred/phpThumbOf#11]
when the phpthumbof filter is used on a modx site installed in subdirectory nothing is output but the original TV image link alias. The error.log reports and extensive error with a bunch of messed up file paths in the following format:

your_sites_root_path/MODX_subdirectory//MODX_subdirectory/assets/...

this problem has been duplicated by hlight, sushi, evf, joz3, rwt and me on the modx forums.

see these threads for further details:
http://modxcms.com/forums/index.php/topic,59490.20.html
http://modxcms.com/forums/index.php/topic,61682.msg354424.html

**Comment by Expanism** [comment]
I have the same issue. 
Related post: http://modxcms.com/forums/index.php/topic,63182.0.html

**Comment by 01iv3r** [comment]
Wow!! I just tried MadeMyDay's fix and it worked! Here's it is:

"What I recently discovered: If you change this line in core/model/phpthumb/phpthumb.class.php

CODE:
$AbsoluteFilename = $this->config_document_root.dirname(@$_SERVER['PHP_SELF']).DIRECTORY_SEPARATOR.$filename;

(around line 1030)

in

CODE:
$AbsoluteFilename = $this->config_document_root.$filename;

everything works again. Debugged this over 2 hours but cannot tell you why this happens."

note: it's line 1033 in phpthumb.class.php for me

**Comment by bertoost** [comment]
I also have this, and fixed like above. I saw this was fixed in 2.1-rc3!

**Comment by 01iv3r** [comment]
apparently the issue still occurs in some cases even with the fix. 

awesome though that this issues looks to be fixed for real 2.1 :)
